//
//  MockAPISearchAssertData.swift
//  iOSEngineerCodeCheckTests
//
//  Created by Masakiyo Tachikawa on 2022/02/06.
//  Copyright © 2022 YUMEMI Inc. All rights reserved.
//

import Foundation

// MARK: -------------------- mockAPISearchCount7AssertData
///
///
///
let mockAPISearchCount7AssertData: [[String: String]] = [
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "11169 stars",
        "watchers": "22269 watchers",
        "forks": "5 forks",
        "openIssues": "9 open issues",
        "fullName": "yumemi-inc/ios-engineer-codecheck",
        "avatarURL": "https://avatars.githubusercontent.com/u/6687975?v=4",
        "htmlURL": "https://github.com/yumemi-inc/ios-engineer-codecheck",
    ],
    [
        "writtenLanguage": "Written in ",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "forks": "12345 forks",
        "openIssues": "54321 open issues",
        "fullName": "riku3/iOS-training-yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/39666818?v=4",
        "htmlURL": "https://github.com/riku3/iOS-training-yumemi",
    ],
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "1 star",
        "watchers": "1 watcher",
        "forks": "1 fork",
        "openIssues": "1 open issue",
        "fullName": "uhooi/YumemiWeather-iOS",
        "avatarURL": "https://avatars.githubusercontent.com/u/21194714?v=4",
        "htmlURL": "https://github.com/uhooi/YumemiWeather-iOS",
    ],
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "forks": "0 forks",
        "openIssues": "4 open issues",
        "fullName": "fucchi-senpai/ios-training",
        "avatarURL": "https://avatars.githubusercontent.com/u/53225198?v=4",
        "htmlURL": "https://github.com/fucchi-senpai/ios-training",
    ],
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "2 stars",
        "watchers": "2 watchers",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "fullName": "daichikuwa0618/YumemiTraining",
        "avatarURL": "https://avatars.githubusercontent.com/u/31601805?v=4",
        "htmlURL": "https://github.com/daichikuwa0618/YumemiTraining",
    ],
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "fullName": "yoshimasaki/Repo",
        "avatarURL": "https://avatars.githubusercontent.com/u/52738915?v=4",
        "htmlURL": "https://github.com/yoshimasaki/Repo",
    ],
    [
        "writtenLanguage": "Written in Swift",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "fullName": "MilanistaDev/AppIconCorrespondingToDarkMode",
        "avatarURL": "https://avatars.githubusercontent.com/u/8732417?v=4",
        "htmlURL": "https://github.com/MilanistaDev/AppIconCorrespondingToDarkMode",
    ],
]

// MARK: -------------------- mockAPISearchCount201AssertData
///
///
///
let mockAPISearchCount201AssertData: [[String: String]] = [
    [
        "fullName": "dcyuki/yumemi_bot",
        "avatarURL": "https://avatars.githubusercontent.com/u/37479458?v=4",
        "stargazers": "24 stars",
        "watchers": "24 watchers",
        "writtenLanguage": "Written in JavaScript",
        "forks": "4 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/dcyuki/yumemi_bot",
    ],
    [
        "fullName": "yumemi-inc/ios-engineer-codecheck",
        "avatarURL": "https://avatars.githubusercontent.com/u/6687975?v=4",
        "stargazers": "69 stars",
        "watchers": "69 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "5 forks",
        "openIssues": "9 open issues",
        "htmlURL": "https://github.com/yumemi-inc/ios-engineer-codecheck",
    ],
    [
        "fullName": "Kaito-Dogi/android-intern-assignment-yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/49048577?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Kotlin",
        "forks": "4 forks",
        "openIssues": "1 open issue",
        "htmlURL": "https://github.com/Kaito-Dogi/android-intern-assignment-yumemi",
    ],
    [
        "fullName": "yumemi-inc/android-engineer-codecheck",
        "avatarURL": "https://avatars.githubusercontent.com/u/6687975?v=4",
        "stargazers": "66 stars",
        "watchers": "66 watchers",
        "writtenLanguage": "Written in Kotlin",
        "forks": "1 fork",
        "openIssues": "9 open issues",
        "htmlURL": "https://github.com/yumemi-inc/android-engineer-codecheck",
    ],
    [
        "fullName": "daichikuwa0618/YUMEMIwork",
        "avatarURL": "https://avatars.githubusercontent.com/u/31601805?v=4",
        "stargazers": "6 stars",
        "watchers": "6 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/daichikuwa0618/YUMEMIwork",
    ],
    [
        "fullName": "satttto/yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/42766938?v=4",
        "stargazers": "3 stars",
        "watchers": "3 watchers",
        "writtenLanguage": "Written in PHP",
        "forks": "0 forks",
        "openIssues": "1 open issue",
        "htmlURL": "https://github.com/satttto/yumemi",
    ],
    [
        "fullName": "fpob/yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/6289078?v=4",
        "stargazers": "3 stars",
        "watchers": "3 watchers",
        "writtenLanguage": "Written in Python",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/fpob/yumemi",
    ],
    [
        "fullName": "MilanistaDev/StudyGroupEventFetcherForSwiftUI",
        "avatarURL": "https://avatars.githubusercontent.com/u/8732417?v=4",
        "stargazers": "13 stars",
        "watchers": "13 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "3 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/MilanistaDev/StudyGroupEventFetcherForSwiftUI",
    ],
    [
        "fullName": "daichikuwa0618/YumemiTraining",
        "avatarURL": "https://avatars.githubusercontent.com/u/31601805?v=4",
        "stargazers": "2 stars",
        "watchers": "2 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/daichikuwa0618/YumemiTraining",
    ],
    [
        "fullName": "KaiseiYokoyama/yumemi_qrorder",
        "avatarURL": "https://avatars.githubusercontent.com/u/8509057?v=4",
        "stargazers": "2 stars",
        "watchers": "2 watchers",
        "writtenLanguage": "Written in PHP",
        "forks": "0 forks",
        "openIssues": "3 open issues",
        "htmlURL": "https://github.com/KaiseiYokoyama/yumemi_qrorder",
    ],
    [
        "fullName": "dharminderraja/Android-Test-app-2",
        "avatarURL": "https://avatars.githubusercontent.com/u/32354459?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Kotlin",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/dharminderraja/Android-Test-app-2",
    ],
    [
        "fullName": "koux2/YumemiTraining",
        "avatarURL": "https://avatars.githubusercontent.com/u/2197399?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/koux2/YumemiTraining",
    ],
    [
        "fullName": "orpheuslyra/YumemiTraining",
        "avatarURL": "https://avatars.githubusercontent.com/u/4732583?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/orpheuslyra/YumemiTraining",
    ],
    [
        "fullName": "1024ken/YumemiTask",
        "avatarURL": "https://avatars.githubusercontent.com/u/26004951?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/1024ken/YumemiTask",
    ],
    [
        "fullName": "shu-pf/yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/61904065?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Vue",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/shu-pf/yumemi",
    ],
    [
        "fullName": "masa-suzuki-iPhone/yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/71866173?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/masa-suzuki-iPhone/yumemi",
    ],
    [
        "fullName": "kurodadiary/yumemi",
        "avatarURL": "https://avatars.githubusercontent.com/u/41744089?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in ",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/kurodadiary/yumemi",
    ],
    [
        "fullName": "lllttt06/YumemiTest",
        "avatarURL": "https://avatars.githubusercontent.com/u/72681064?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Kotlin",
        "forks": "0 forks",
        "openIssues": "1 open issue",
        "htmlURL": "https://github.com/lllttt06/YumemiTest",
    ],
    [
        "fullName": "uhooi/YumemiWeather-iOS",
        "avatarURL": "https://avatars.githubusercontent.com/u/21194714?v=4",
        "stargazers": "1 star",
        "watchers": "1 watcher",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/uhooi/YumemiWeather-iOS",
    ],
    [
        "fullName": "tsumugisato/YumemiCodeCheck",
        "avatarURL": "https://avatars.githubusercontent.com/u/68152531?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/tsumugisato/YumemiCodeCheck",
    ],
    [
        "fullName": "yumemi-inc/yc",
        "avatarURL": "https://avatars.githubusercontent.com/u/6687975?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in HTML",
        "forks": "0 forks",
        "openIssues": "1 open issue",
        "htmlURL": "https://github.com/yumemi-inc/yc",
    ],
    [
        "fullName": "tamsalanghae/search-repo-coding-test",
        "avatarURL": "https://avatars.githubusercontent.com/u/57677056?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Dart",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/tamsalanghae/search-repo-coding-test",
    ],
    [
        "fullName": "Hyperbolic4183/YumemiWeather",
        "avatarURL": "https://avatars.githubusercontent.com/u/60565914?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "1 fork",
        "openIssues": "2 open issues",
        "htmlURL": "https://github.com/Hyperbolic4183/YumemiWeather",
    ],
    [
        "fullName": "tanobe/practice_with_YumemiWeather",
        "avatarURL": "https://avatars.githubusercontent.com/u/73284586?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/tanobe/practice_with_YumemiWeather",
    ],
    [
        "fullName": "rear0146/YumemiCodeCheckSC",
        "avatarURL": "https://avatars.githubusercontent.com/u/51353838?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in JavaScript",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/rear0146/YumemiCodeCheckSC",
    ],
    [
        "fullName": "dcyuki/yumemi_mp",
        "avatarURL": "https://avatars.githubusercontent.com/u/37479458?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in JavaScript",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/dcyuki/yumemi_mp",
    ],
    [
        "fullName": "ThatGuySami/YumemiYasui",
        "avatarURL": "https://avatars.githubusercontent.com/u/50159146?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in ",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/ThatGuySami/YumemiYasui",
    ],
    [
        "fullName": "HirotoIshikawa/YumemiWeather",
        "avatarURL": "https://avatars.githubusercontent.com/u/34052553?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/HirotoIshikawa/YumemiWeather",
    ],
    [
        "fullName": "miurakazuma67/yumemiTraining",
        "avatarURL": "https://avatars.githubusercontent.com/u/68637266?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Swift",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/miurakazuma67/yumemiTraining",
    ],
    [
        "fullName": "lilium513/YumemiTodo",
        "avatarURL": "https://avatars.githubusercontent.com/u/10419597?v=4",
        "stargazers": "0 stars",
        "watchers": "0 watchers",
        "writtenLanguage": "Written in Kotlin",
        "forks": "0 forks",
        "openIssues": "0 open issues",
        "htmlURL": "https://github.com/lilium513/YumemiTodo",
    ],
]
